/**
 http://www.w3.org/TR/SVG/coords.html#InterfaceSVGPreserveAspectRatio
 
 interface ZG_SVGPreserveAspectRatio {
 
 // Alignment Types
 SVG_PRESERVEASPECTRATIO_UNKNOWN = 0;
 SVG_PRESERVEASPECTRATIO_NONE = 1;
 SVG_PRESERVEASPECTRATIO_XMINYMIN = 2;
 SVG_PRESERVEASPECTRATIO_XMIDYMIN = 3;
 SVG_PRESERVEASPECTRATIO_XMAXYMIN = 4;
 SVG_PRESERVEASPECTRATIO_XMINYMID = 5;
 SVG_PRESERVEASPECTRATIO_XMIDYMID = 6;
 SVG_PRESERVEASPECTRATIO_XMAXYMID = 7;
 SVG_PRESERVEASPECTRATIO_XMINYMAX = 8;
 SVG_PRESERVEASPECTRATIO_XMIDYMAX = 9;
 SVG_PRESERVEASPECTRATIO_XMAXYMAX = 10;
 
 // Meet-or-slice Types
 SVG_MEETORSLICE_UNKNOWN = 0;
 SVG_MEETORSLICE_MEET = 1;
 SVG_MEETORSLICE_SLICE = 2;
 
 attribute unsigned short align setraises(DOMException);
 attribute unsigned short meetOrSlice setraises(DOMException);
 };
 */
#import <Foundation/Foundation.h>

@interface ZG_SVGPreserveAspectRatio : NSObject

typedef enum ZG_SVG_PRESERVEASPECTRATIO
{	
	// Alignment Types
    ZG_SVG_PRESERVEASPECTRATIO_UNKNOWN = 0,
    ZG_SVG_PRESERVEASPECTRATIO_NONE = 1,
    ZG_SVG_PRESERVEASPECTRATIO_XMINYMIN = 2,
    ZG_SVG_PRESERVEASPECTRATIO_XMIDYMIN = 3,
    ZG_SVG_PRESERVEASPECTRATIO_XMAXYMIN = 4,
    ZG_SVG_PRESERVEASPECTRATIO_XMINYMID = 5,
    ZG_SVG_PRESERVEASPECTRATIO_XMIDYMID = 6,
    ZG_SVG_PRESERVEASPECTRATIO_XMAXYMID = 7,
    ZG_SVG_PRESERVEASPECTRATIO_XMINYMAX = 8,
    ZG_SVG_PRESERVEASPECTRATIO_XMIDYMAX = 9,
    ZG_SVG_PRESERVEASPECTRATIO_XMAXYMAX = 10
} ZG_SVG_PRESERVEASPECTRATIO;

typedef enum ZG_SVG_MEETORSLICE
{
	// Meet-or-slice Types
    ZG_SVG_MEETORSLICE_UNKNOWN = 0,
    ZG_SVG_MEETORSLICE_MEET = 1,
    ZG_SVG_MEETORSLICE_SLICE = 2
} ZG_SVG_MEETORSLICE;

@property(nonatomic) ZG_SVG_PRESERVEASPECTRATIO align;
@property(nonatomic) ZG_SVG_MEETORSLICE meetOrSlice;

@end
